source "http://rubygems.org"

gem "sinatra", "~>1.3.0"
gem "activesupport", "~>2.3.0", :require => "active_support"
gem "json"
gem "faraday", :git => "git://github.com/lostisland/faraday.git"
gem "oauth", "~>0.4"
gem "twitter", :git => "git://github.com/bgreenlee/twitter.git"
gem "dm-core", "~>1.2.0"
gem "dm-timestamps", "~>1.2.0"
gem "dm-mysql-adapter", "~>1.2.0"
gem "dm-migrations", "~>1.2.0"
gem "system_timer"