source "http://rubygems.org"

gem "sinatra", "~>1.3.0"
gem "activesupport", "~>2.3.0", :require => "active_support"
gem "json"
gem "oauth", "~>0.4"
gem "twitter", "~>2.2.8"
gem "dm-core", "~>1.2.0"
gem "dm-timestamps", "~>1.2.0"
gem "dm-mysql-adapter", "~>1.2.0"
gem "dm-migrations", "~>1.2.0"
gem "system_timer"