source "http://rubygems.org"

gem "sinatra", "~>1.4.0"
gem "activesupport", "~> 3.2.11"
gem "json", "~> 1.8.1"
gem "faraday", "~> 0.9.0"
gem "oauth", "~>0.4"
gem "twitter", :git => "git://github.com/sferik/twitter.git"
gem "dm-core", "~>1.2.0"
gem "dm-timestamps", "~>1.2.0"
gem "dm-mysql-adapter", "~>1.2.0"
gem "dm-sqlite-adapter"
gem "dm-migrations", "~>1.2.0"
gem "erubis"
gem "tzinfo"
